say ( "Bu bitkiler (1) Hasun Zindanindan toplandi. " ) 
say ( "Atini tekrar canlandiracaklar. " ) 
say ( "Haydi atini çagiralim! " ) 
wait ( ) 
say ( "Ata bitkileri yedir ve bekle. " ) 
say ( "[DELAY value=400]. . .[/DELAY]" ) 
horse . summon ( ) 
wait ( ) 
say ( "Atin canlanmaya basladi. " ) 
say ( "Gelecekte atini beslemeyi unutma. " ) 
if pc . countitem ( "50057" ) >= 1 then 
pc . removeitem ( "50057" , 1 ) 
horse . revive ( ) 
end 
