say_title ( "Seyis:" ) 
say ( "" ) 
say ( "Görevini basariyla tamamladin." ) 
say ( "Ata binebilmek için bir at resmine ihtiyacin var." ) 
say ( "Bunu saglayabilmem biraz zaman alacak." ) 
say ( "Yarin yine gel." ) 
say ( "At resminin fiyatinin 100.000 Yang oldugunu" ) 
say ( "unutma!" ) 
if is_test_server ( ) then 
pc . setqf ( "make_time" , get_time ( ) + 10 ) 
else 
pc . setqf ( "make_time" , get_time ( ) + number ( 8 , 16 ) * 60 * 60 ) 
end 
setstate ( "wait" ) 
