say_title ( "Seyis:" ) 
say ( "" ) 
say_reward ( "30 dakikada 20 Yabani okçu" ) 
say_reward ( "öldür ve dön!" ) 
say ( "" ) 
local b = select ( "Bir baska" , "iptal" ) 
if 1 == b then 
elseif 2 == b then 
say_title ( "Seyis:" ) 
say ( "" ) 
say ( "Yeterlilik testini iptal etmek istiyor musun?" ) 
say ( "" ) 
local b = select ( "Evet" , "Hayir, sadece bir sakaydi." ) 
if 1 == b then 
say_title ( "Seyis:" ) 
say ( "" ) 
say ( "Basaracagindan emin oldugunda tekrar dene." ) 
say ( "" ) 
setstate ( "start" ) 
q . done ( ) 
elseif 2 == b then 
say_title ( "Seyis:" ) 
say ( "" ) 
say ( "Hata yapacak kadar zamanin yok." ) 
say ( "Acele et! O yabani askerleri öldür " ) 
say ( "ve dön!" ) 
else 
say ( "UNBEKANNTE TASTE [" .. b .. "]" ) 
end 
else 
say ( "UNBEKANNTE TASTE [" .. b .. "]" ) 
end 
